"""create messages table

Revision ID: cac88fd5b5ed
Revises: 48b4163d9ac6
Create Date: 2025-03-16 09:23:07.536839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac88fd5b5ed'
down_revision: Union[str, None] = '48b4163d9ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('content', sa.String(length=255), nullable=False),
        sa.Column('queue_id', sa.Integer(), sa.ForeignKey('queues.id', ondelete="CASCADE"), nullable=True),
        sa.Column('topic_id', sa.Integer(), sa.ForeignKey('topics.id', ondelete="CASCADE"), nullable=True),
        sa.Column('status', sa.Enum('pending', 'processed', name="message_status"), default="pending"),
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    pass
    # ### end Alembic commands ###
